version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: contagem_prod
      POSTGRES_USER: contagem_user
      POSTGRES_PASSWORD: 'S1stem@_C0nt@gem_2026_Prod!'
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    networks:
      - portaleletricos
    deploy:
      placement:
        constraints:
          - node.role == manager

  backend:
    image: ghcr.io/agenciageraleads/sistema-de-contagem/backend:latest
    environment:
      DATABASE_URL: postgresql://contagem_user:S1stem%40_C0nt%40gem_2026_Prod%21@db:5432/contagem_prod?schema=public
      JWT_SECRET: 'WKbn tCxvaJTl3aopVn6nq0INIuwKci0ycjimdVXZ4YQ='
      JWT_EXPIRES_IN: '7d'
      PORT: 3001
      NODE_ENV: production
    depends_on:
      - db
    networks:
      - portaleletricos
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=1
        - traefik.http.routers.contagem-api.rule=Host(`contagem.vps.portaleletricos.com.br`) && PathPrefix(`/api`)
        - traefik.http.routers.contagem-api.entrypoints=websecure
        - traefik.http.routers.contagem-api.tls.certresolver=letsencryptresolver
        - traefik.http.routers.contagem-api.priority=2
        - traefik.http.services.contagem-api.loadbalancer.server.port=3001

  frontend:
    image: ghcr.io/agenciageraleads/sistema-de-contagem/frontend:latest
    environment:
      API_URL: https://contagem.vps.portaleletricos.com.br/api
      NEXT_PUBLIC_API_URL: https://contagem.vps.portaleletricos.com.br/api
    networks:
      - portaleletricos
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=1
        - traefik.http.routers.contagem-web.rule=Host(`contagem.vps.portaleletricos.com.br`)
        - traefik.http.routers.contagem-web.entrypoints=websecure
        - traefik.http.routers.contagem-web.tls.certresolver=letsencryptresolver
        - traefik.http.routers.contagem-web.priority=1
        - traefik.http.services.contagem-web.loadbalancer.server.port=3000

networks:
  portaleletricos:
    external: true

volumes:
  pgdata_prod:
    driver: local
